### ISSUE TITLE
Multiple Lights controlled independently in PD patches

### ISSUE THREAD

**Issue by PHREDD71** [jmej/MIDI2DMX#11]
I was wondering if it is possible to control two different lights daisy chained together with different addresses with the current code and PD files? I have tried getting it to work and cannot seem to figure it out.

My setup is two PAR lights connected to the MIDI2DMX board I built. I then set the first light to Address 1 and then the second light to Address 2.

Any guidance is much appreciated. I am just a hobbyist so all of this is pretty new.

**Comment by sid8580** [comment]
You can definitely control multiple lights as long as they are
DMX-addressable (do you know specifically, numerically what DMX channel
they are set to receive on?), and you are sending MIDI data to the
MIDI2DMX on the right MIDI channel and CC # (can you also confirm your MIDI
output?).

If it's not working, but you know you have for example, the first par can
at 10 and the second one set to 11, you can send MIDI values via CC 10 and
11 to the MIDI2DMX and see if it works... if not, try changing the MIDI
channel (without changing the CC #) until you've run through all 16 MIDI
channels.  Off the top of my head I don't remember which channel(s) the
MIDI2DMX picks up by default but that can be set in the Arduino code.

It can be helpful to verify your MIDI equipment is sending the CC data you
think it is, too.

If it's still not working and you're 100% sure your MIDI channel, CC #'s
and DMX channel settings are in agreement, I would check your wiring.  If
you are using equipment that uses screw terminals, rather than DMX cables
(which btw aren't exactly the same as XLR cables, though shorter ones can
work) - it is easy to get the wires mixed up.

**Comment by jmej** [comment]
Most lights take up a handful of DMX channels as well..so if you only have a few it can be easy to set the starting channel of light 1 to channel 1, and light two to channel 11... what way you have maybe 1 - 2- 3 for r-g-b of the first light and 11-12-13 for r-g-b of the second light. But it all depends on channels your lights need. Often you might have channel 7 for brightness - with the above addressing scheme your second light would respond to brightness on channel 17.

I hope this helps!
