### ISSUE TITLE
CC mapping to DMX fade not working well in Ableton clip 

### ISSUE THREAD

**Issue by rosscopcoltrane** [jmej/MIDI2DMX#13]
Hi there and thanks for this project, it’s really great to have a go at midi control of lights. 

I’m using Ableton to control simple can fades through a Liteputer dx402a. Right now I’ve managed to get midi CC 2 to control DMX001, CC3 to control DMX002 etc etc. The lights are plugged in via Edison plugs, they aren’t addressed or DMX compatible, just plain old cans. 

When trying to sequence my CC values it seems like I’m getting glitches, but on further inspection, the envelope seems to be divided into 3 or 4 zones, it’s hard to tell. This (while kind of workable), gives me the effective resolution of 30 or something, a bit steppy really. Perhaps there’s something I’ve done wrong.. 

Could the liteputer be causing this?

**Comment by rosscopcoltrane** [comment]
DMX start address is set on Liteputer as 001 by the way.

**Comment by jmej** [comment]
I think you may be in the wrong place - this is the issues thread for the midi2dmx diy project.. Im not familiar with the liteputer line of devices.. are you also using a midi2dmx board?

**Comment by jmej** [comment]
Midi2DMX sends out a 7 bits of resolution - so basically there is a *2 for every value.. to translate from midi (0-127) to DMX (0-254).

Sending out higher resolution would be a nice feature - I've considered an NRPN solution - or using midi pitchbend - but for now that's the best it can do.

It sounds like you're having another issue with the liteputer and without that hardware I'm unable to test - but it should be seeing movement on every other step as your'e doing a fade.. which should look much smoother than what it sounds like you're seeing. I'm closing this issue for now - since I don't think this is an issue on the midi2DMX side of things.
